### ISSUE TITLE
Call GnuPG Asynchronously

### ISSUE THREAD

**Issue by biergaizi** [jvenant/passff#106]
Normally, calling gpg to decrypt for a password is a lightweight and fast operation, but it is true only if the key is stored on the computer. 

On my homemade smartcard, it takes 10 seconds to perform RSA-4096 calculations. If I use it with passff, the entire FireFox will also hang for 10 seconds. High performance smartcards may spend 3 seconds on it. In future, GnuPG may even support encryption over network. Fix the lockup issue will enable more flexibilities of GnuPG.

Calling GnuPG asynchronously with a progressbar may be a good idea.

**Comment by phryneas** [comment]
I'm using a smartcard and for me it is working asynchronously. Which OS are you on?
