### ISSUE TITLE
GUI does not update in Private Browsing

### ISSUE THREAD

**Issue by matachi** [jvenant/passff#109]
First, great add-on!

However, I have noticed a small problem:

1. Open a private window (Ctrl+Shift+P).
2. Click on the PassFF button in the toolbar.
3. Try to do some navigation. It does not update.

I recorded a video of it: https://vimeo.com/142854015 As you can see, you have to close and reopen the PassFF menu for it to update.

I'm running Firefox 41.0.1 on Fedora 22 with PassFF 0.1.27 .

**Comment by sometoby** [comment]
I suppose this is the same problem as documented in #94. If I am mistaken, please re-open this issue.
