### ISSUE TITLE
GPG Agent Read on Initialization

### ISSUE THREAD

**Issue by psycotica0** [jvenant/passff#116]
I haven't looked at the code a lot to confirm, but I think this is related to #17 and #23.

I was getting the same `tty` issue, and digging into it by replacing `pass` with my own logging wrapper I was seeing that the `GPG_AGENT_INFO` variable was empty.

Setting the variable in my wrapper based on the env file worked.

Then I disabled the plugin and enabled it again, and the variable was provided and things worked properly.
The file didn't yet exist when I first installed the plugin.

Is this plausible, or have I also just seen an ephemeral issue?

**Comment by jvenant** [comment]
the gpg agent info variable is set at each start of the plugin, the first time you try to access a password.
So disabling/enabling the plugin will reset the variable. But stopping/starting Firefox should also reset the variable (from what I know).
The plugin try first to get the info from the gpgAgentInfo file preference (default .gpg-agent-info). If it fail, it will just use the variable from the firefox environment variables (if found)

I don't know exactly when your .gpg-agen-info file is created. But if it is before your first access a password, it should work...

**Comment by psycotica0** [comment]
Right, but I think I didn't have my GPG agent setup properly when I first turned on the plugin, and then I restarted the agent at some point as well.

So, after that point it never worked and only gave me errors about `dev/tty`.
It was only through debugging that I tried turning the plugin off and back on again to get the current gpg agent info.

**Comment by jvenant** [comment]
So I assume we can say that this is an ephemeral issue caused by changes in GPG agent setup will using passFF. Right ?

**Comment by psycotica0** [comment]
I'll leave that up to you. I believe it was an issue caused by my GPG agent changing, but it resulted in the plugin never working after that until I turned it off and back on again, and giving confusing error messages.
