### ISSUE TITLE
Unable to enable addon with FF 44 Beta

### ISSUE THREAD

**Issue by craftyguy** [jvenant/passff#118]
When I install passff and enable it, I receive the following error in the browser log, and passff never loads (i.e. I do not see the black P icon): 

1451962709214	addons.manager	WARN	Exception calling callback: TypeError: redeclaration of let PassFF (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@invicem.pro.xpi!/bootstrap.js -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@invicem.pro.xpi!/modules/common.js:4:1) JS Stack trace: @resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@invicem.pro.xpi!/bootstrap.js -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@common.js:4:1 < startup/</<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@bootstrap.js:59:5 < startup/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/clayton/.mozilla/firefox/yjok33e1.default/extensions/passff@bootstrap.js:57:3 < safeCall@AddonManager.jsm:173:5 < makeSafe/<@AddonManager.jsm:189:25 < Handler.prototype.process@Promise-backend.js:934:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:813:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:747:1 < waitForSyncCallback@async.js:102:7 < makeSpinningCallback/callback.wait@async.js:156:27 < _handlerListener@addonsreconciler.js:632:9 < onEnabled@addonsreconciler.js:645:5 < AMI_callAddonListeners@AddonManager.jsm:1793:11 < AMP_callAddonListeners@AddonManager.jsm:2817:5 < XPI_updateAddonDisabledState@XPIProvider.jsm:4598:11 < AddonWrapper_userDisabledSetter@XPIProvider.jsm:6970:9 < cancelUninstall@extensions.xml:1819:13 < oncommand@about:addons:1:1

**Comment by ticoombs** [comment]
Confirmed happening under Mozilla Firefox 46.0a1 (Trunk) as well.

**Comment by craftyguy** [comment]
After scouring the commit log, I found this commit from November: https://github.com/jvenant/passff/commit/d7f47e29b6e77bab3c5e681545be681afdb43770

I pulled the latest code from here, built it, and the issue seems to be resolved by this commit since the addon now successfully loads.. hopefully a new 'official' release is pushed out soon!
