### ISSUE TITLE
Addon causes Firefox to freeze with certain input into location bar

### ISSUE THREAD

**Issue by untitaker** [jvenant/passff#121]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1239871

>Enter any of the following strings into the location bar (without quotes) and hit enter:

>* ".a.b"
>* ".example.com"
>* "https://.example.com"

**Comment by jvenant** [comment]
Funny one ^_^. I gonna fix this asap.
Thank you.

**Comment by untitaker** [comment]
Awesome, thanks!
