### ISSUE TITLE
cannot install in FF 43.0.4

### ISSUE THREAD

**Issue by svenXY** [jvenant/passff#133]
Hi,

FF 43 (and above) directly deactivate your nice plugin due to a missing signature.

See 
https://support.mozilla.org/de/kb/Add-on-Signierung-in-Firefox?as=u&utm_source=inproduct
for details (or the corresponding page in english, sorry).

I know I can disable the feature that signing is required, but that would be global then.

Any chance, passff will be signed soon?

Thanks,
Sven

**Comment by jvenant** [comment]
Is this what you are looking for ?
https://addons.mozilla.org/fr/firefox/addon/passff/

**Comment by svenXY** [comment]
Yes, thanks. Couldn't find it in the german/english store.
