### ISSUE TITLE
Sign Addon

### ISSUE THREAD

**Issue by famfop** [jvenant/passff#136]
I've just installed this package. It took me a while and I had to set the "xpinstall.signatures.required" variable in about:config to false as the addon is not "signed".
Basically my question is whether you could sign the addon. 
For me to get this working as described above I followed [this page](http://winaero.com/blog/enable-unsigned-add-ons-disabled-by-firefox-43/).

**Comment by jvenant** [comment]
Signed version can be found on the mozilla web site : https://addons.mozilla.org/fr/firefox/addon/passff

**Comment by famfop** [comment]
Oh, thanks a lot and sorry for the spam, didn't see that. Maybe you could add a line in the README as I followed it and maybe others do, too?

**Comment by jvenant** [comment]
Hi, not a spam ^_^, you're right, I modified the README.md to include link to the signed version
