### ISSUE TITLE
Passff no longer works in Firefox Nightly for several weeks

### ISSUE THREAD

**Issue by m-wynn** [jvenant/passff#139]
I'm not sure where to get logs from, but for the past few weeks, the PassFF menu button will not appear.  I assume Fuel was finally removed?

The only logs I see in the browser console are:

### Upon disabling the addon
`1457994028962	addons.xpi	WARN	Exception running bootstrap method shutdown on passff@invicem.pro: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.removeSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js :: PassFF.windowListener.removeUI :: line 276"  data: no] Stack trace: PassFF.windowListener.removeUI()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js:276 < PassFF.uninit()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js:196 < shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js:74 < this.XPIProvider.callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4673 < this.XPIProvider.updateAddonDisabledState()@resource://gre/modules/addons/XPIProvider.jsm:4792 < AddonWrapper.prototype.userDisabled()@resource://gre/modules/addons/XPIProvider.jsm:7137 < set_userDisabled()@extensions.xml:1084 < oncommand()@about:addons:1`

### Upon enabling the addon
`1457994030759	addons.manager	WARN	Exception calling callback: TypeError: Cc['@mozilla.org/fuel/application;1'] is undefined (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/modules/preferences.js:36:9) JS Stack trace: PassFF.Preferences.init@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@invicem.pro.xpi!/bootstrap.js -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@preferences.js:36:9 < startup/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mwynn/.mozilla/firefox/profilefolder-1456979761178/extensions/passff@bootstrap.js:67:3 < safeCall@AddonManager.jsm:179:5 < makeSafe/<@AddonManager.jsm:195:25 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < Promise*this.PromiseWalker.scheduleWalkerLoop@Promise-backend.js:747:11 < this.PromiseWalker.schedulePromise@Promise-backend.js:779:7 < Promise.prototype.then@Promise-backend.js:454:5 < this.DeferredSave.prototype.saveChanges@DeferredSave.jsm:194:7 < this.XPIDatabase.saveChanges@XPIProviderUtils.js:469:19 < this.XPIDatabase.setAddonProperties@XPIProviderUtils.js:1369:5 < this.XPIProvider.updateAddonDisabledState@XPIProvider.jsm:4750:5 < AddonWrapper.prototype.userDisabled@XPIProvider.jsm:7137:9 < set_userDisabled@extensions.xml:1084:11 < oncommand@about:addons:1:1`

**Comment by jvenant** [comment]
Could you give a try the [this version](https://github.com/jvenant/passff/releases/tag/0.1.30).
If it's ok, I will push it on the mozilla website

**Comment by arashm** [comment]
I just tested the new version and I passff icon is being shown on the address bar again. I also tested "Fill" and "Fill and Submit" actions which worked fine on my Firefox (47.0a2 2016-03-19)

**Comment by m-wynn** [comment]
I wasn't about to get the link in your comment to work, but the latest commit to master works fine here.

**Comment by jvenant** [comment]
I fixed the link
