### ISSUE TITLE
passff doesn't work

### ISSUE THREAD

**Issue by daniel-sousa-me** [jvenant/passff#142]
I can see the entry list in passff, but I can't get any password. If I ask passff to Fill, it puts the name of the entry in every field. If I ask passff to Display, the password shows as (null).
pass on the cli is working as expected. I tried both Through shell and Direct call and always get the same results

I enabled the log and it outputs:
> [PassFF] Execute pass Object { command: "/usr/bin/pass", arguments: Array[2], environment: Array[7], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done(), bufferedOutput: false, workdir: null, libc: "libc.so.6" } bootstrap.js:37
> [PassFF] [subprocess] getlimit: maxFD=65536
>  bootstrap.js:37
> [PassFF] [subprocess] subprocess started; got PID 23331
>  bootstrap.js:37
> [PassFF] [subprocess] trying to close stdin
>  bootstrap.js:37
> [PassFF] [subprocess] Closing Stdin
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stderr: initialising library with libc.so.6
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stderr: waitpid signaled subprocess stop, exitcode=512
>  bootstrap.js:37
> [PassFF] [subprocess] got 59 bytes from stderr
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stderr: poll returned HUP
>  bootstrap.js:37
> [PassFF] [subprocess] got 0 bytes from stderr
>  bootstrap.js:37
> [PassFF] [subprocess] Pipe stderr closed
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stdout: initialising library with libc.so.6
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stdout: waitpid returned with errno=10
>  bootstrap.js:37
> [PassFF] [subprocess] Got msg from stdout: poll returned HUP
>  bootstrap.js:37
> [PassFF] [subprocess] Pipe stdout closed
>  bootstrap.js:37
> [PassFF] [subprocess] Cleanup called
>  bootstrap.js:37
> [PassFF] [subprocess] trying to close stdin
>  bootstrap.js:37
> [PassFF] pass script execution ok

**Comment by jvenant** [comment]
Just googled "poll returned HUP" and found this http://stackoverflow.com/questions/27803885/webide-firefox-os-simulator-operation-failed-connecting-to-runtime/27865423#27865423
Might help....?

**Comment by daniel-sousa-me** [comment]
That did not help.

When I Google "passff poll returned HUP", there are results with logs from other people that don't have this problem.

**Comment by jvenant** [comment]
did you try adding --login in the shell arguments of the through shell call method ?

**Comment by daniel-sousa-me** [comment]
I just tried and nothing changed.

If I run firefox from the shell, I see the normal pass output on the stdout and it works as I expected if I put there the password.
Is this how I should have been using passff?

**Comment by jvenant** [comment]
How do you organise your password repository ?

**Comment by daniel-sousa-me** [comment]
Currently, I don't. It was imported from keepass and I didn't use any folders there.
Why might this relevant?

**Comment by phryneas** [comment]
it asks you _on the shell_ for the password if you are using passff?

do you have a gpg-agent running?

**Comment by daniel-sousa-me** [comment]
Yes, it does.

I don't know anything about gpg-agent, but 'pgrep gpg-agent' returns a pid.

**Comment by phryneas** [comment]
mhh.. passff invokes pass, which invokes passff, which invokes gpg, which invokes gpg-agent (if it is running & configured), which invokes pinentry.
could you check if you have pinentry configured for console input rather that pinentry-gtk or pinentry-qt? that would be my guess.

**Comment by daniel-sousa-me** [comment]
I figured out the problem! I was having problems with gpg2 and so I edited pass to force it to use gpg1, which doesn't use pinentry.

Now I am having problems with pinentry, but I'll continue trying to figure them out by myself.

Thank you very much for your help

**Comment by phryneas** [comment]
I'm glad I could be of help :)
Good luck!

**Comment by jvenant** [comment]
Thank you Lenz, always here for good clue ;)
