### ISSUE TITLE
Firefox 45.0.1 Config is broken

### ISSUE THREAD

**Issue by Philelis** [jvenant/passff#143]
Heyho, I've testet your last release and that is an error that occurs, if you want to configure something.
One version earlier works ;)
<img width="858" alt="error" src="https://cloud.githubusercontent.com/assets/9850839/14256567/e975ef26-fa99-11e5-9a2a-cd3dedd98e85.png">

> 
> XML-Verarbeitungsfehler: Nicht definierte Entität
> Adresse: chrome://passff/content/preferencesWindow.xul
> Zeile Nr. 77, Spalte 17:                <label tooltiptext="&enter-behavior-tooltip;" value="&enter-behavior;"/>
> ----------------^

`19:06:54.967 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:06:56.482 [PassFF] Location changed "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:06:56.482 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:06:56.482 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "" } bootstrap.js:37
19:06:56.484 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:06:56.485 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:07:02.735 [PassFF] Location changed "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:07:02.735 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:07:02.735 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/new", search: "" } bootstrap.js:37
19:07:02.737 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:07:02.738 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:07:03.073 [PassFF] Location changed "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:07:03.073 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:07:03.073 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/new", search: "" } bootstrap.js:37
19:07:03.075 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:07:03.076 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:07:06.660 [PassFF] Tab Selected <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" linkedpanel="panel-3-3" label="Add-ons-Manager" visibleLabel="Add-ons-Manager" fadein="true" image="chrome://mozapps/skin/extensions/extensionGeneric-16.png" afterselected="true"> bootstrap.js:37
19:07:06.660 [PassFF] createContextualMenu about:newtab bootstrap.js:37
19:07:06.660 [PassFF] Search items for: URL { href: "about:newtab", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "newtab", search: "" } bootstrap.js:37
19:07:06.662 [PassFF] Matching items: Array [  ] bootstrap.js:37
19:07:06.662 [PassFF] Create children menu list Array [ Object, Object, Object ] undefined bootstrap.js:37
19:07:07.078 [PassFF] aaaaa  bootstrap.js:37
19:07:07.081 [PassFF] Content loaded load { target: HTMLDocument → about:newtab, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 0, originalTarget: HTMLDocument → about:newtab, explicitOriginalTarget: HTMLDocument → about:newtab, NONE: 0, CAPTURING_PHASE: 1 } false 0 bootstrap.js:37
19:07:15.589 [PassFF] Location changed about:addons bootstrap.js:37
19:07:15.589 [PassFF] createContextualMenu about:addons bootstrap.js:37
19:07:15.589 [PassFF] Search items for: URL { href: "about:addons", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "addons", search: "" } bootstrap.js:37
19:07:15.591 [PassFF] Matching items: Array [  ] bootstrap.js:37
19:07:15.591 [PassFF] Create children menu list Array [ Object, Object, Object ] undefined bootstrap.js:37
19:07:15.726 [PassFF] Location changed about:addons bootstrap.js:37
19:07:15.727 [PassFF] createContextualMenu about:addons bootstrap.js:37
19:07:15.727 [PassFF] Search items for: URL { href: "about:addons", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "addons", search: "" } bootstrap.js:37
19:07:15.728 [PassFF] Matching items: Array [  ] bootstrap.js:37
19:07:15.728 [PassFF] Create children menu list Array [ Object, Object, Object ] undefined bootstrap.js:37
19:07:16.173 [PassFF] Content loaded load { target: XULDocument → about:addons, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 0, originalTarget: XULDocument → about:addons, explicitOriginalTarget: XULDocument → about:addons, NONE: 0, CAPTURING_PHASE: 1 } false 0 bootstrap.js:37
19:08:20.445 [PassFF] Tab Selected <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" linkedpanel="panel-3-2" label="New Issue · jvenant/passff" visibleLabel="New Issue · jvenant/passff" fadein="true" image="https://assets-cdn.github.com/favicon.ico" beforeselected="true"> bootstrap.js:37
19:08:20.445 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:08:20.445 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/new", search: "" } bootstrap.js:37
19:08:20.447 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:08:20.448 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:15.428 [PassFF] Tab Selected <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" linkedpanel="panel-3-4" label="Neuer Tab" visibleLabel="Neuer Tab" last-tab="true" fadein="true" last-visible-tab="true"> bootstrap.js:37
19:11:15.428 [PassFF] createContextualMenu about:newtab bootstrap.js:37
19:11:15.428 [PassFF] Search items for: URL { href: "about:newtab", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "newtab", search: "" } bootstrap.js:37
19:11:15.430 [PassFF] Matching items: Array [  ] bootstrap.js:37
19:11:15.430 [PassFF] Create children menu list Array [ Object, Object, Object ] undefined bootstrap.js:37
19:11:15.876 [PassFF] aaaaa  bootstrap.js:37
19:11:15.879 [PassFF] Content loaded load { target: HTMLDocument → about:newtab, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 0, originalTarget: HTMLDocument → about:newtab, explicitOriginalTarget: HTMLDocument → about:newtab, NONE: 0, CAPTURING_PHASE: 1 } false 0 bootstrap.js:37
19:11:20.494 [PassFF] Tab Selected <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" linkedpanel="panel-3-2" label="New Issue · jvenant/passff" visibleLabel="New Issue · jvenant/passff" fadein="true" image="https://assets-cdn.github.com/favicon.ico" beforeselected="true"> bootstrap.js:37
19:11:20.494 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:11:20.494 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/new", search: "" } bootstrap.js:37
19:11:20.496 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:20.496 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:24.021 [PassFF] Location changed "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:11:24.021 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/new" bootstrap.js:37
19:11:24.022 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/new", search: "" } bootstrap.js:37
19:11:24.023 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:24.024 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:24.343 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. passff
19:11:24.568 [PassFF] Tab Selected <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" linkedpanel="panel-3-5" label="Mac OSX · Issue #47 · jvenant/passff" visibleLabel="Mac OSX · Issue #47 · jvenant/passff" fadein="true" image="https://assets-cdn.github.com/favicon.ico" selected="true"> bootstrap.js:37
19:11:24.568 [PassFF] createContextualMenu "https://github.com/jvenant/passff" bootstrap.js:37
19:11:24.568 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff", search: "" } bootstrap.js:37
19:11:24.570 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:24.571 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:24.857 [PassFF] aaaaa  bootstrap.js:37
19:11:24.859 [PassFF] Content loaded load { target: HTMLDocument → 47, isTrusted: true, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 0, originalTarget: HTMLDocument → 47, explicitOriginalTarget: HTMLDocument → 47, NONE: 0, CAPTURING_PHASE: 1 } false 0 bootstrap.js:37
19:11:25.778 [PassFF] Location changed "https://github.com/jvenant/passff" bootstrap.js:37
19:11:25.779 [PassFF] createContextualMenu "https://github.com/jvenant/passff" bootstrap.js:37
19:11:25.779 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff", search: "" } bootstrap.js:37
19:11:25.781 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:25.782 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:25.809 [PassFF] Location changed "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:11:25.809 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:11:25.809 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "" } bootstrap.js:37
19:11:25.811 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:25.812 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:26.258 [PassFF] Location changed "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:11:26.259 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues" bootstrap.js:37
19:11:26.259 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "" } bootstrap.js:37
19:11:26.261 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:26.262 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:29.272 [PassFF] Location changed "https://github.com/jvenant/passff/issues?q=is%3Aissue+is%3Aclosed" bootstrap.js:37
19:11:29.272 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues?q=is%3Aissue+is%3Aclosed" bootstrap.js:37
19:11:29.272 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "?q=is%3Aissue+is%3Aclosed" } bootstrap.js:37
19:11:29.273 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:29.274 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:29.697 [PassFF] Location changed "https://github.com/jvenant/passff/issues?q=is%3Aissue+is%3Aclosed" bootstrap.js:37
19:11:29.698 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues?q=is%3Aissue+is%3Aclosed" bootstrap.js:37
19:11:29.698 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "?q=is%3Aissue+is%3Aclosed" } bootstrap.js:37
19:11:29.699 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:29.700 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:39.536 [PassFF] Location changed "https://github.com/jvenant/passff/issues?utf8=%E2%9C%93&q=mac" bootstrap.js:37
19:11:39.536 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues?utf8=%E2%9C%93&q=mac" bootstrap.js:37
19:11:39.536 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "?utf8=%E2%9C%93&q=mac" } bootstrap.js:37
19:11:39.538 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:39.539 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:40.227 [PassFF] Location changed "https://github.com/jvenant/passff/issues?utf8=%E2%9C%93&q=mac" bootstrap.js:37
19:11:40.227 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues?utf8=%E2%9C%93&q=mac" bootstrap.js:37
19:11:40.227 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues", search: "?utf8=%E2%9C%93&q=mac" } bootstrap.js:37
19:11:40.229 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:40.229 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:43.559 [PassFF] Location changed "https://github.com/jvenant/passff/issues/47" bootstrap.js:37
19:11:43.559 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/47" bootstrap.js:37
19:11:43.560 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/47", search: "" } bootstrap.js:37
19:11:43.561 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:43.561 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined bootstrap.js:37
19:11:45.324 [PassFF] Location changed "https://github.com/jvenant/passff/issues/47" bootstrap.js:37
19:11:45.324 [PassFF] createContextualMenu "https://github.com/jvenant/passff/issues/47" bootstrap.js:37
19:11:45.324 [PassFF] Search items for: URL { href: "https://github.com/jvenant/passff/i…", origin: "https://github.com", protocol: "https:", username: "", password: "", host: "github.com", hostname: "github.com", port: "", pathname: "/jvenant/passff/issues/47", search: "" } bootstrap.js:37
19:11:45.325 [PassFF] Matching items: Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] bootstrap.js:37
19:11:45.326 [PassFF] Create children menu list Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 7 weitere… ] undefined`

**Comment by jvenant** [comment]
Could give me the german translation for 
"Behavior of enter key"
"This determines the default behavior when pressing the enter key on an item in the menu"

If someone reading this can also give me the russian translation, it would be great

**Comment by phryneas** [comment]
Verhalten der Enter-Taste.
Bestimmt das Standardverhalten, wenn die Enter-Taste gedrückt wird, während ein Eintrag im Menü ausgewählt ist.
