### ISSUE TITLE
 Error executing pass script (FF46)

### ISSUE THREAD

**Issue by mcnesium** [jvenant/passff#149]
After using passff happily for quite a while I got this error message today:

![ Error executing pass script ](https://cloud.githubusercontent.com/assets/476060/14861337/19e3161e-0cad-11e6-9c01-91179dca21bd.png)

and the passff popup remains empty. The error message reappears, when I try to refresh passff. As Firefox upgraded to version 46 today, this might be a coincidence…

**Comment by phryneas** [comment]
in the preferences, did you enter the full path to your pass binary/shell binary?

**Comment by mcnesium** [comment]
Unfortunately I cannot tell. Whenever I hit the options button either from the passff popup or fromt he Firefox addons manager, I get this:
![bildschirmfoto 2016-05-02 um 14 06 17](https://cloud.githubusercontent.com/assets/476060/14954032/1aed3ed4-106f-11e6-816e-d44b6fce44e2.png)

**Comment by phryneas** [comment]
that's a bug that occured for a while because a german translation was missing. could you try with the most recent version please?

**Comment by mcnesium** [comment]
Installed [most recent release 0.1.30-fix](https://github.com/jvenant/passff/releases/download/0.1.30-fix/passff.xpi) (had to [override addon-signing](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_override-add-on-signing-advanced-users)) but no difference :(

**Comment by mcnesium** [comment]
still the same with [Firefox 46.0.1](https://www.mozilla.org/en-US/firefox/46.0.1/releasenotes/)

**Comment by phryneas** [comment]
oh, sorry, this has not been merged yet. @jvenant could you please merge https://github.com/jvenant/passff/pull/148 ?

**Comment by mcnesium** [comment]
the current release fixed the language thing, but lead to #151.
