### ISSUE TITLE
bash process with high CPU, Firefox not responding

### ISSUE THREAD

**Issue by mcnesium** [jvenant/passff#151]
This is on Firefox 46.0.1/OSX. Steps to reproduce:

1. [create a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)
2. install passff extension via addons view - passff icon appears in menu bar
3. set the correct full path to pass, i.e. `/usr/local/bin/pass` in my case as I installed it using [homebrew](http://brew.sh)
4. restart Firefox
5. passff icon is gone in the menu bar
6. bash process running at >90% CPU appears in process manager, firefox process is shown as "not responding"
7. kill that evil bash process
8. passff icon appears, firefox process is back alive, application responding normally
9. click "reload" in passff
10. GOTO 5.

**Comment by phryneas** [comment]
could you do a pstree on the console?
seems like something in pass is not responding, and as pass itself spawns about 20 different processes it might be interesing to see in which state that happens

**Comment by mcnesium** [comment]
\-+= 01918 mcnesium /Applications/Firefox.app/Contents/MacOS/firefox
       |--- 02088 mcnesium /Applications/Firefox.app/Contents/MacOS/plugin-container.app/Contents/MacOS/plugin-container -greomni /Applications/Firefox.app/Contents/Resources/omni.ja -appomni /Applications/
       \--- 02096 mcnesium bash /usr/local/bin/pass

**Comment by phryneas** [comment]
could you please try the steps described in the issues paragraph in https://github.com/jvenant/passff/blob/master/README.md ?

**Comment by mcnesium** [comment]
I filled in all the fields, restarted Firefox, now there is no weird bash process coming up, but I got back to #149 -.-

**Comment by phryneas** [comment]
The initial error message I presume?

Does /bin/bash exist in that folder on your system? Is the pass binary installed in /usr/local/bin/pass ? Could you try `-l -i` instead of --login as a paramter?

**Comment by mcnesium** [comment]
yes, its `/usr/local/bin/pass` as well as `/usr/local/bin/bash` but it looks like the entries are not saved correctly. After another Firefox restart, everything in the Pass Script view was set back to default values.

**Comment by phryneas** [comment]
hm... if you enable logging and open the browser console, do you get output from PassFF?

**Comment by phryneas** [comment]
@mcnesium - as we pinpointed this to another issue, could you close this one please?
We can try to solve the issue in #152

**Comment by mcnesium** [comment]
ok :)
