### ISSUE TITLE
Removing this annoying error!

### ISSUE THREAD

**Issue by jpalcantara** [jvenant/passff#154]
I installed PassFF in which I shouldn't have!  However I uninstalled the addons and I can seem to remove this message.  I am on a MAC OS 10.11.5 (15F34) running Firefox 46.0.1

  I had the same issue on my linux and I removed it by clearing everything, on the MAC I have cleared everything uninstalled FF and deleted the profile.  The problem remains.

Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isExecutable]

**Comment by phryneas** [comment]
This error occurs when passff tries to execute pass, but passff has not been configured to the correct pass executable location - wich you can do in the options of the passff plugin.

It is however, not likely that your are getting this error after disabling or uninstalling the plugin. Plugins that are not installed can not exdcute code and thus not cause error messages.
If this were the case, you would have found a bug in Firefox, in that it does not actually uninstall plugins.
As you even removed the profile, this seems unlikely.

If I had to guess: are you sure that you are not starting firefox with a rogue profile that is somewhere you don't expect or firefox is starting in some weird multi-profile fashion?
