### ISSUE TITLE
Usage on Windows

### ISSUE THREAD

**Issue by Gfurst** [jvenant/passff#159]
So can someone elaborate how use this along on Windows Firefox?

In multisystem setup, syncing up the pass-storage. What are requirements for the Windows usage? And maybe possible use cases. It should also be interesting to have this info on the frontpage readme.

Cheers

**Comment by jvenant** [comment]
I assume you'll have to use cygwin or an equivalent.
there is also a windows client you could try : https://github.com/mbos/Pass4Win
For general question about how to make pass works under Windows, you could also try the pass mailling list : https://lists.zx2c4.com/mailman/listinfo/password-store

**Comment by Gfurst** [comment]
Yeah, I haven't set it up yet but was aiming to use pass4win, however the question was more directed at passFF plugin, like if it would work with pass4win.
Or do they all have same dependency, that is to have a basic pass setup?

**Comment by phryneas** [comment]
For usage of passff with windows, you need to get the original pass running, not pass4win.

I'd recommend setting up an msys2 shell, installing pass inside it is not very difficult. Then you can use the through-the-shell mode of passff.

**Comment by DeastinY** [comment]
Hi all,
I set up pass inside the msys2 shell and tried to set up the "through-the-shell" mode.
Still could not get it to work. When reloading the error is 

> Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]

Will continue looking into it and keep this post updated.

**Comment by DeastinY** [comment]
Got that issue fixed using the solution from @rettgerst.
https://github.com/jvenant/passff/issues/152

**Comment by jvenant** [comment]
Good news !
Thank you for your feedback
