### ISSUE TITLE
Crazy bank's login page... How to handle?

### ISSUE THREAD

**Issue by plague-doctor** [jvenant/passff#162]
Is there a way to use passff to deal with login pages which looks like that one: https://ibanking.stgeorge.com.au/ibank/loginPage.action
In order to login, one must put: 
 - username (Access Number)
 - security number (another static number)
 - Internet Password (the alpha-numeric password), and
 - Issue number (taken from the list)
Can you suggest how to bite that? Or the only option is to change bank?

**Comment by jvenant** [comment]
Hi,
You would probably be able to fill 2 of the fields putting the inputs name (ie: userId, securityNumber) in the password and login input names preferences in the passff.
For the 2 others, I'm afraid I have no solution for you for now :/

**Comment by plague-doctor** [comment]
I understand. Thank you for your answer. Anyway, I hope you will extend this plugin to be able to fill out the forms too.

**Comment by jvenant** [comment]
This is a revival, but maybe the last merge request (https://github.com/jvenant/passff/pull/164) could help you with your bank form.
you can now add inputfieldname: inputfieldvalue in your password data file
