### ISSUE TITLE
Please publish updated versions to mozilla

### ISSUE THREAD

**Issue by viq** [jvenant/passff#40]
Please publish new releases to mozilla, currently (possibly due to Sync) the plugin keeps reverting to version available in mozilla addons.

**Comment by viq** [comment]
How about current version?

**Comment by jvenant** [comment]
Hi viq,

Sure it's a good idea, but I would like to do a full review next time.
And I still have an AMO issue to solve first here : #33.
I don't have any idea of how to solve it for now.

**Comment by viq** [comment]
The version at mozilla is 8 releases behind...
