### ISSUE TITLE
Uses category name instead of password entry

### ISSUE THREAD

**Issue by matmo** [jvenant/passff#45]
I set up my pass according to the passff guidelines:
* www
    * facebook.com (contains password, login: , url: )

However passff (sometimes?) fills in "www" as username (e.g. on facebook)

**Comment by jvenant** [comment]
I can't reproduce this behaviors

1. Does this happen always (and systematically) on the same entries ?
2. Are you sure that the fields names defined in the "Login field names" option match the one in your pass entry ?
3. could you try renaming www in something else (eg. Internet)
4. Could you provide me a pass store sample (without sensible data) that would allow me te reproduce the issue ?
