### ISSUE TITLE
Not working with GPG 2.1

### ISSUE THREAD

**Issue by tampakrap** [jvenant/passff#48]
https://www.gnupg.org/faq/whats-new-in-2.1.html

Right now passff can't decrypt anything with gpg 2.1. My assumption is that the deprecation of $GPG_AGENT_INFO is the issue here. I am willing to provide further debug info if needed.

**Comment by jvenant** [comment]
Hi tampakrap,

Thank you for your feedback. 

I'm using gpg (GnuPG) 2.1.1 and have no issue with it.
From my understanding, gpg 2.1 should now work without any special configuration.
And indeed, on my Archlinux, I don't have any GPG_AGENT_INFO environment variable anymore. And I don't need a .gpg-agent-info file neither. Everything steel works as expected.

Could you give me some more details about the error ? You can find that in the web console

**Comment by tampakrap** [comment]
I tried with a completely clean environment and it does work fine! I assume there is something in my old environment that is causing gpg to malfunction, probably some old gpg 2.0 files in my .gnupg directory. I will let you know if I find anything useful, but for now I'm closing this one, thanks for the feedback!

**Comment by indiv0** [comment]
I was having this issue as well, with GPG 2.1

I got it to work by setting `Pass command` to `/bin/bash` and `Pass command line arguments` to `--login /usr/bin/pass`.

This is on Arch Linux.

**Comment by phryneas** [comment]
with the most recent release you can use just "shell invocation" which will have the same effect
