### ISSUE TITLE
support for symlinks in password-store tree

### ISSUE THREAD

**Issue by tampakrap** [jvenant/passff#49]
At work I have two LDAP accounts (a production and a development one), and a bunch of websites working with the one or the other LDAP account. Since I tend to change quite frequently the password of the development LDAP account, I thought of creating symlinks in my password store tree, like this:

* site1.job.com.gpg (works with ldap-account1)
* site2.job.com.gpg (works with ldap-account2)
* site3.job.com.gpg -> site2.job.com.gpg

In passff I see the following:

site1.job.com
site2.job.com
site3.job.com.gpg -> site2.job.com

When I try to display the site3 contents in passff, I get the following error:
`Error: site3.job.com.gpg -> site2.job.com is not in the password store.`

PS: I believe this issue should be low prio, as it is quite a corner case

**Comment by jvenant** [comment]
Should works now with this release [v1-pre-release-15](https://github.com/jvenant/passff/releases/tag/v1-pre-release-15)

**Comment by tampakrap** [comment]
I highly appreciate that you implemented this so fast! Unfortunately it is not working. The symlink is showing up in the list now as site2.job.com.gpg. The .gpg part needs also to be removed so that it can properly be detected by passff

**Comment by jvenant** [comment]
sorry for this, But I'm totally blind with this issue because on my computer symlinks don't work at all. Even using pass script directly.
So I made a new release  [v1-pre-release-16](https://github.com/jvenant/passff/releases/tag/v1-pre-release-16) removing .pgp extension.
Let me know if it solve your problem.... Or not ^_^

**Comment by tampakrap** [comment]
Your git tag in v1-pre-release-16 is wrong, it points to the same as -15, BUT:
I decided that the .gpg issue should be fixed on pass directly, as it now shows symlinks like that: `site1.job.com.gpg -> site2.job.com`
while it should instead show: `site1.job.com -> site2.job.com`

I have a patch for pass and I'm going to submit it, which also solves my issue. Thus, please revert 6386b2e5d389c7d4bc936d8c125fc41eeed59036 and remove -16 tag (which points to wrong commit either way).

Sorry for the trouble, and again thanks a lot for your fast actions

**Comment by jvenant** [comment]
ok, I revert

**Comment by jvenant** [comment]
Did you try removing the .gpg extension from your symlink...?

**Comment by tampakrap** [comment]
sure, it doesn't work:
Error: site1.job.com is not in the password store.

**Comment by jvenant** [comment]
Ok, so it's definitely a pass script issue

**Comment by tampakrap** [comment]
http://lists.zx2c4.com/pipermail/password-store/2015-January/001332.html
