### ISSUE TITLE
better search for items matching url

### ISSUE THREAD

**Issue by netslovdlyasnov** [jvenant/passff#51]
Hello.
you look for item's key in url, sometimes it's not right because item's key can be '1' for example. and it can match.
So I offer to search for url's host in item's key. But maybe it should be better to use other url parsing method like https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/url
Here is my replacement:  
getUrlMatchingItems : function(url) {
    var urls = url.split('/');
    if (urls==null && urls.length <3) { return; }

    return this._items.filter(function(item) {
      return !item.isField() && urls[2]==item.key;
    });
  },

Now it gives the right items for sites where I have lots of accounts.

Please check.
Thanks.

**Comment by jvenant** [comment]
Hello @netslovdlyasnov,

Thank you very much for your feedback and for your code. Your request makes sens.

I chose to implement it using the addon sdk url api as you suggest. So now, key search will match the hostname exclusively.
If it cause some trouble to some people, let me know. I'll try to find a solution to fit everybody needs.
Release here : [v1-pre-release-17](https://github.com/jvenant/passff/releases/tag/v1-pre-release-17)

**Comment by netslovdlyasnov** [comment]
or even better:
  getUrlMatchingItems : function(urlStr) {
    let url = new URL(urlStr);
    log.debug("Find items for :", url);
    return this._items.filter(function(item){
      let path=item.fullKey();
      return !item.isField() && path.indexOf(url.host) >= 0;
    });
  },

**Comment by jvenant** [comment]
I'm afraid that doing this will drastically change the way passff choose the contextual pass entries to display. And for some passff users, it will just not work any more.

Currently, because passff search for the pass entry name in the url, it match sub-domains :
"mysite.com" pass entry will match "mysite.com", "www.mysite.com", "wiki.mysite.com" and so on.
This will not work anymore using your method.

Maybe removing the subdomain from the url would do the trick, but I have to think a little bit about it. To be sure there will be no side effect for the users

**Comment by netslovdlyasnov** [comment]
ok, now I see why you are searching for a key in url, instead of url in the key.
Seems to me there should be done few searches removing subdomain while only one dot '.' left in hostname. Just as an opinion.

**Comment by jvenant** [comment]
The last [release](https://github.com/jvenant/passff/releases/tag/v1-pre-release-22) should work as you expect.

**Comment by netslovdlyasnov** [comment]
Well, not really.
For example for 'vk.com' I get:
netvkino.ru
vk.com
vkontakte.ru
vkontakte.ru/1
vkontakte.ru/2

Right in this order. I think exact match should be the first. and others are not really a match.

**Comment by jvenant** [comment]
Ok, I understand that.
But you know, it's difficult to find an algorithm that match everybody needs. Especially when you don't want to have any constrains on how people repository is organized.
For example, on my own repo, my google accounts are inside a "google" directory, not "google.com" or "google.fr" or whatever. So from my point of view, top-level domain is not relevant when searching for entries.
By the way, I'll try to implement some kind of smart sort algorithm that will put the most relevant entries at the top of the list. I hope that it will be enough to match your needs.

**Comment by jvenant** [comment]
I add a sort feature to the matching results array.
Here is an example of how it works for http://my.subdomain.domain.com url (the higher the score is, the best the match is)

if pass entry fullpath match "my.subdomain.domain.com" get a 404 score
if pass entry fullpath match "subdomain.domain.com" get a 403 score
if pass entry fullpath match "domain.com" get a 402 score
--- com : this one is omitted (tld match is ommitted)

if pass entry fullpath match "my.subdomain.domain" get a 303 score
if pass entry fullpath match "subdomain.domain" get a 302 score
if pass entry fullpath match "domain" get a 301 score

if pass entry fullpath match "my.subdomain" get a 202 score
if pass entry fullpath match "subdomain" get a 201 score

if pass entry fullpath match "my" get a 101 score

I hope it's clear enough

**Comment by netslovdlyasnov** [comment]
That's a lot better. 
I am satisfied now :)

Best wishes.
