### ISSUE TITLE
Cygwin - no icon when settings are (presumably) good

### ISSUE THREAD

**Issue by bjauy** [jvenant/passff#52]
I'm trying to run passff in Cygwin. I've tried putting parameters as in #38 and error message doesn't appear anymore. 

The problem is that after correcting settings and restarting Firefox I don't see the icon in the bar. When I restore settings to defaults, both error message and icon return. I've noticed that icon won't appear until you close the message.

Is there any way I could debug startup process? Additionally, where are logs (from ```"enable logs"``` option) being stored?

**Comment by jvenant** [comment]
Hello,

After enabling the logs in the PassFF options, you can see logs in the browser console Ctrl-Shift-j or Tools/Web Developper/Browser Console

Let me know if it help you to solve your problem. Or give me some relevant information from the logs.

**Comment by phryneas** [comment]
Please also check that you use double-backslashes. I edited my comment in #38 accordingly.

**Comment by bjauy** [comment]
@phryneas Yes, I've read comments below and tried both single and double backslashes.

@jvenant I'll give it a try later and let you know.

**Comment by bjauy** [comment]
It warns about non-existing ```length``` function in pass.js:190. 

When I have removed the parentheses (so it becomes ```.trim().length```), the icon returned.

**Comment by jvenant** [comment]
ok, my mistake. length is a property, not a function.
I applied the fix on the master branch.

Thank you
