### ISSUE TITLE
setGpgAgentEnv: adding a little bit too much Environment

### ISSUE THREAD

**Issue by phryneas** [jvenant/passff#53]
Hi,
as of upgrading the plugin, pass is not working any more, it comes down to this:

the first popen (getting the password list) works well:
command:"C:\\Users\\phry\\cygwin\\bin\\bash.exe --login /bin/pass"
environment:Array[4] [
"HOME=C:\\Users\\phry\\"
"DISPLAY=:0.0"
"PASSWORD_STORE_DIR=.password-store"
"PASSWORD_STORE_GIT=.password-store/.git"
]

the second popen (looking up a password) does not work so well and fails with an exeception.
command:"C:\\Users\\phry\\cygwin\\bin\\bash.exe --login /bin/pass mypass"
environment:Array[8] [
"HOME=C:\\Users\\phry\\"
"DISPLAY=:0.0"
"PASSWORD_STORE_DIR=.password-store"
"PASSWORD_STORE_GIT=.password-store/.git"
"SSH_AUTH_SOCK=/tmp/ssh-dqw123fwSZ5/agent.4480; export SSH_AUTH_SOCK;"
"SSH_AGENT_PID=208; export SSH_AGENT_PID;"
"echo Agent pid 208;"
""
]

As you see, the environment variable seems to contain a lot of junk, and I suspect this is what makes the popen fail.

Out of suspicion, I commented out the lines in "preferences.setGpgAgentEnv", where you set these variables, and after that, pass is being executed.
(still with some problems with the PATH to the gpg executable, but I believe this error is just in my configuration and another thing I will have to clean up in my environment ;) ).

So if you have the time, it would be great if you could fix that environment parsing part.

Thanks a lot!

**Comment by jvenant** [comment]
Hi @phryneas,

I assume that the "SSH_*" variables are extracted from your ~/.gpg-agent-info file.

Obviously, cygwin gpg-agent version may create this file on the first call and generate some additional bash commands that should not be part of the environment variables array.

If commenting the preferences.setGpgAgentEnv line works for you, I assume you use GPG >= 2.1. Those versions don't need env variables any more.
If you want to avoid code modification, you could also try to :
* change your gpg-agent configuration to prevent gpg-agent-info file creation (don't know if it is possible)
* set the "Gpg agent info file" preference to a not existing file. Doing this, PassFF will fallback trying to get variables from the Firefox environment instead.

On my side, I'll try to make the variables extraction from the file a little bit smarter ^_^.

**Comment by phryneas** [comment]
Hi @jvenant,
unfortunately I'm stuck with GPG 2.0.26 until gpg4win makes the switch to 2.1 (or I search for another pre-compiled version.. I'm NOT going to compile gpg myself on a windows box, that's awful ;) ) - that version still uses the ~/.gpg-agent-info file.

So commenting out the setGpgAgentEnv is just a temporary fix as it could even try to spawn a new agent on each call - have not been experimenting with that too much ;)

Also, preventing creation on that file is no real option here, as my command line use still needs that file.

So I'm eagerly awainting a "smarter" parsing from you ^_^

Something like matching for /^([^=]+=[^;]+)/ should do the trick, don't you think?

(Sorry, I would fix this myself and create a pull request, but I am curently swamped in work so I just don't have the time to do that for at least one more month :( )

**Comment by jvenant** [comment]
Ok, done here : [v1-pre-release-21](https://github.com/jvenant/passff/releases/tag/v1-pre-release-21).
Thank you for the regex :smile:

**Comment by phryneas** [comment]
Works like a charm, thanks a lot!

**Comment by jvenant** [comment]
Cool :smile:
