### ISSUE TITLE
Plugin hangs on startup

### ISSUE THREAD

**Issue by tophattom** [jvenant/passff#55]
When I start the plugin the icon doesn't show up in the toolbar. Activity monitor shows a bash process with 100% processor usage. After killing the process, the icon appears in the toolbar but no passwords are shown.

pass is located at /usr/local/bin/pass (installed via Homebrew) and that's what I set in the preferences as pass command. Setting the command to just pass didn't work. It spawned the following error:
![nayttokuva 2015-2-24 kello 23 38 38](https://cloud.githubusercontent.com/assets/654307/6359812/4a3f7e86-bc7e-11e4-86a5-b68aa40b8318.png)
 I also tried setting User home and Pass home but they didn't have any effect.

Firefox 37.0a2 on OS X 10.9.5

**Comment by jvenant** [comment]
looks very similar to #47

**Comment by jvenant** [comment]
There is lot of literature about 0x80520001 on the internet. But I didn't found any clear explanation.
Any way, it looks like its linked to the way OSX manage paths. OSX, for some reason, don't like the way the paths are defined in passff.

So I made a special version of the plugin that don't set the workdir. It will prevent one call to nslFile.initWithPath. The only last call to this method will be for the pass command itself (/usr/local/bin/pass)
You can find it here [passff-test.xpi](https://github.com/jvenant/passff/releases/download/v1-pre-release-22/passff-test.xpi)

If this version works for you, well... that's a good news. I will report the modification on the master. Hopping that there won't be any side effect for other people.
If you still have the same behavior, you can try changing the path to the pass script. I don't know macos, but you may have multiple representation for the same path.
For example : adding "file://", escaping the "/", removing the first "/",....

**Comment by tophattom** [comment]
Using just pass as the command doesn't work in the test version either.

Running the latest release with the following options
![nayttokuva 2015-2-25 kello 20 49 35](https://cloud.githubusercontent.com/assets/654307/6377881/0f550b30-bd30-11e4-8ca2-3ec7853cf26e.png)

Results in a bash process taking up 100% of the processor and this log:
````
"[PassFF]" "Try to retrieve Gpg agent variable from file /Users/jaakko/" bootstrap.js:32
"[PassFF]" "Preferences initialised" [object Object] bootstrap.js:32
"[PassFF]" "Execute pass" [object Object] bootstrap.js:31
"[PassFF]" "Can't read file. Retrieve Gpg agent variable from environment" bootstrap.js:32
"[PassFF]" "Set Gpg agent variable :" Array[3] bootstrap.js:31
````

After I killing the bash process the log shows:
````
"[PassFF]" "Try to retrieve Gpg agent variable from file /Users/jaakko/" bootstrap.js:32
"[PassFF]" "Preferences initialised" [object Object] bootstrap.js:32
"[PassFF]" "Execute pass" [object Object] bootstrap.js:31
"[PassFF]" "Can't read file. Retrieve Gpg agent variable from environment" bootstrap.js:32
"[PassFF]" "Set Gpg agent variable :" Array[3] bootstrap.js:31
"[PassFF]" 15 "/usr/local/bin/pass: line 298: /usr/local/bin/getopt: No such file or directory
" "" bootstrap.js:33
"[PassFF]" "init" bootstrap.js:31
"[PassFF]" "Wait documents" bootstrap.js:31
"[PassFF]" "Documents found" bootstrap.js:31
"[PassFF]" "Add panel to new window" bootstrap.js:31
"[PassFF]" "createContextualMenu" "about:addons" bootstrap.js:31
"[PassFF]" "Search items for :" [object URL] bootstrap.js:31
"[PassFF]" "Create children menu list" Array[0] undefined bootstrap.js:31
"[PassFF]" "Wait panels" bootstrap.js:31
"[PassFF]" "Panels found" bootstrap.js:31
````

I'm curious about the line which looks like it's trying to run /usr/local/bin/getopt and it's not found. getopt is located in /usr/bin/getopt on my machine. Maybe this could be the source of the problem? Is passff, for some reason, aasuming that pass and getopt are located in the same directory?

**Comment by phryneas** [comment]
That would look more like an error in your installation of pass.

pass determines the path to getopt with the following line ( from http://git.zx2c4.com/password-store/tree/src/platform/darwin.sh ):
GETOPT="$(brew --prefix gnu-getopt 2>/dev/null || { which port &>/dev/null && echo /opt/local; } || echo /usr/local)/bin/getopt"


this would result result in /usr/local/bin/getopt if
    brew --prefix gnu-getopt
and 
    which port
fail.

Does it work from the terminal for you? Then it might still be a passff problem (PATH wrong, not finding brew or port) - otherwise, it might be a pass problem.

**Comment by tophattom** [comment]
pass is working just fine from the terminal

**Comment by phryneas** [comment]
Hmmm.

I don't have a mac and thus am no homebrew user, just reading myself a little bit into this.

* by default, brew should install to /usr/local/bin (default HOMEBREW_PREFIX is /usr/local )
* the pass brew package requires the gnu-getopt package
* so gnu-getopt should be installed by brew - and be symlinked  to /usr/local/bin

The scenarios I can think of why getopt is in /usr/bin, but not in /usr/local/bin would be

* you installed homebrew to another folder ( /usr prefix? ) 
* you had getopt installed already, so homebrew did not install that dependency

but anyways, in both such cases 

    brew --prefix gnu-getopt 

should return the correct path anyway, so the main problem seems to be that passff can't find the brew binary.

could you please add

    echo $PATH > /tmp/passpath

as second line to your _/usr/local/bin/pass_ (or wherever it is), reload passff, and paste the contents of _/tmp/passpath_ here?

**Comment by tophattom** [comment]
Homebrew installs packages to ````/usr/local/Cellar```` and symlinks them to ````/usr/local/bin````. gnu-getopt package is installed but it is not symlinked to ````/usr/local/bin```` since OS X already provides getopt. However, it is linked to ````/usr/local/opt/gnu-getopt````.
````
~ ❯❯❯ brew --prefix gnu-getopt
/usr/local/opt/gnu-getopt
````
which is correct. getopt binary can be found in ````/usr/local/opt/gnu-getopt/bin/getopt````.

So I have two versions of getopt: one, packaged with OSX, located in /usr/bin/ and the other installed by Homebrew. Anyways, the pass script should be working as supposed to: 
````
GETOPT="$(brew --prefix gnu-getopt 2>/dev/null || { which port &>/dev/null && echo /opt/local; } || echo /usr/local)/bin/getopt"
````
should return ````/usr/local/opt/gnu-getopt/bin/getopt````, right?


I added the line you asked. When I reloaded passff the $PATH was:
````
/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
````
and when I ran pass from terminal
````
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
````

brew is intalled in ````/usr/local/bin/brew````

**Comment by jvenant** [comment]
passff retrieve the PATH environment variable from the Firefox environment.
So it means that the PATH variable of the environment you use to launch Firefox (your desktop I assume) is not the same that the PATH of your CLI.
do you know how to change your desktop PATH variable ? 
* if yes, could you try adding the value of your CLI PATH variable to your desktop one ?
* if no, I will do a new version allowing you to set the PATH in the passff preferences. But to be honest, I'm not very comfortable with this solution : PATH variable could be a little be tricky to set. And for me, it's up to the parent (launcher) process to define the children environment.

You could also try launching firefox from your CLI

**Comment by tophattom** [comment]
I'll try fiddling with PATH later today.

Could you add a preference to *append* stuff to the Firefox PATH? That way you could leave it blank if everything if working.

**Comment by phryneas** [comment]
What weirds me is that /usr/local/bin is in the FF path, so it should find the brew binary and everything should work as intended.

Can you please test two more things?
What is the output of

    PATH="/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:." brew --prefix gnu-getopt

and is

    PATH="/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:." pass

working?

**Comment by tophattom** [comment]
````
~ ❯❯❯ PATH="/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:." brew --prefix gnu-getopt                 ⏎
/usr/local/opt/gnu-getopt
~ ❯❯❯ PATH="/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:." pass
Password Store
└── www
    └── facebook.com.gpg
````
This is starting to seem like witchcraft or something.

**Comment by phryneas** [comment]
Yup, definitely witchcraft.

Does this work?

In the pass options, set
"_pass command_" to "_/bin/bash_" and "_pass command line arguments_" to "_--login /usr/local/bin/pass_"

**Comment by tophattom** [comment]
That works! Thank you very much!

**Comment by phryneas** [comment]
@jvenant maybe it would be generally a good idea to let the user specify a shell that will be run as login shell (so that bashrc, zshrc or whateverrc are evaluated for PATH) - that would circumvent all PATH problems - if it runs on the command line, it will always run in passff, too.

**Comment by jvenant** [comment]
Ok, I'll try to do that. I reopen the issue : as a reminder

**Comment by jvenant** [comment]
By the way, once again, thank you very much @phryneas for your contribution :wink:

**Comment by phryneas** [comment]
You're welcome. I really like this project - but I should really stop my procastination now and get back to learning ^^
