### ISSUE TITLE
[subprocess-related?] passff shows only the first 71 items

### ISSUE THREAD

**Issue by phryneas** [jvenant/passff#59]
Hi,
I just noticed this one:

passff shows only the first 71 of my 170 passwords.

I digged around a bit and it seems that subprocess returns the first 71 lines and then the last line (depending on content, sometimes the last line or no line), so I guess this is a subprocess error.

I will report this to subprocess too, but wanted to report it here, too, so that it is documented.

**Comment by phryneas** [comment]
see https://github.com/bit/subprocess/issues/8

**Comment by phryneas** [comment]
Aaand we've got a winner.

`tree -C` produces outpout that is different from what Firefox expects as UTF-8-conform.

Setting the environment variable ``TREE_CHARSET="windows-1252"`` in ``.bash_profile`` solves the problem for me as it causes tree to use normal ASCII symbols instead of some fancy unicode.


Maybe this would be worth noting in the readme section?

PS: ``TREE_CHARSET="ISO-8859-1"`` works too and should be more multiplatformy ;)

**Comment by phryneas** [comment]
Additionally, it might prove interesting to add a debug listener on

    subprocess.registerDebugHandler(function(msg){ /**/ });

that looks for messages containing ``String conversion failed``  subsequently tries again with another charset, maybe one of the two I mentioned above - or at least warns the user.

**Comment by phryneas** [comment]
One more thing to add... tree now gives me this crap *facepalm*

    |-- firefox
    |   |-- account
    |   &middot;-- account_new

I'll try to look into that tomorrow. Maybe another environment variable to add to the REAME or something...

**Comment by phryneas** [comment]
whoa, you're fast!

you seriously rule :+1:

**Comment by phryneas** [comment]
final note from me - I did some testing on my linux machine now:

% TREE_CHARSET="windows-1252" tree -C test           

    test
    |-- file1
    `-- test2
        `-- file2

% TREE_CHARSET="ISO-8859-1" tree -C test

    test
    |-- file1
    &middot;-- test2
        &middot;-- file2


% TREE_CHARSET="UTF-8" tree -C test

    test
    ├── file1
    └── test2
        └── file2

I'll validate this behavour on my windows box later, if I don't post any more you can assume it's the same there.

**Comment by jvenant** [comment]
So basically, using ISO-8859-15 charset would be the best no ? 
I could remove the "middot" hack...

**Comment by phryneas** [comment]
I just had a look at the tree source, this if from ``colors.c`` and should be interesting.

      static const char*latin1_3[]={
        "ISO-8859-1", "ISO-8859-1:1987", "ISO_8859-1", "latin1", "l1", "IBM819",
        "CP819", "csISOLatin1", "ISO-8859-3", "ISO_8859-3:1988", "ISO_8859-3",
        "latin3", "ls", "csISOLatin3", NULL
      };

      static const char*windows[]={
        "ISO-8859-1-Windows-3.1-Latin-1", "csWindows31Latin1",
        "ISO-8859-2-Windows-Latin-2", "csWindows31Latin2", "windows-1250",
        "windows-1251", "windows-1253", "windows-1254", "windows-1255",
        "windows-1256", "windows-1256", "windows-1257", NULL
      };


      static const struct linedraw cstable[]={
        { latin1_3,    "|  ",              "|--",            "&middot;--",     "&copy;"   },
        { iso8859_789, "|  ",              "|--",            "&middot;--",     "(c)"      },
        { shift_jis,   "\204\240 ",        "\204\245",       "\204\244",       "(c)"      },
        { euc_jp,      "\250\242 ",        "\250\247",       "\250\246",       "(c)"      },
        { euc_kr,      "\246\242 ",        "\246\247",       "\246\246",       "(c)"      },
        { iso2022jp,   "\033$B(\"\033(B ", "\033$B('\033(B", "\033$B(&\033(B", "(c)"      },
        { ibm_pc,      "\263  ",           "\303\304\304",   "\300\304\304",   "(c)"      },
        { ibm_ps2,     "\263  ",           "\303\304\304",   "\300\304\304",   "\227"     },
        { ibm_gr,      "\263  ",           "\303\304\304",   "\300\304\304",   "\270"     },
        { gb,          "\251\246 ",        "\251\300",       "\251\270",       "(c)"      },
        { utf8,        "\342\224\202\302\240\302\240",
        "\342\224\234\342\224\200\342\224\200", "\342\224\224\342\224\200\342\224\200", "\302\251" },
        { big5,        "\242x ",           "\242u",          "\242|",          "(c)"      },
        { viscii,      "|  ",              "|--",            "`--",            "\371"     },
        { koi8ru,      "\201  ",           "\206\200\200",   "\204\200\200",   "\277"     },
        { windows,     "|  ",              "|--",            "`--",            "\251"     },
        { NULL,        "|  ",              "|--",            "`--",            "(c)"      }
      };


Looks like ISO-8859-15 only gives that output because it is unknown - same for windows-1252 which does not seem included. Both those will then somehow fall back to the NULL behaviour, but I think that is not the most consistent way.

I would go with a windows encoding - maybe ``ISO-8859-1-Windows-3.1-Latin-1`` ?

**Comment by phryneas** [comment]
( btw. as a feedback on  v1-pre-release-23: works fine on my linux box using zsh as shell. will try windows later. don't really know where else to give that feeback aside from opening a new issue ;) )
