### ISSUE TITLE
UTF-8 characters not displayed correctly

### ISSUE THREAD

**Issue by bricewge** [jvenant/passff#63]
If some entries contain UTF-8 characters such as accented letters they are not displayed correctly.
For example `Université` become `Universit\303\251`.

**Comment by jvenant** [comment]
Does it work when you use pass script directly ?

**Comment by bricewge** [comment]
Yes, using pass from the command line correctly display UTF-8 characters.

**Comment by jvenant** [comment]
I can't reproduce. I tried using accents and Russian characters, everything works.
I think it's something about your Firefox execution environment.

Could you try using the "Through shell" approach please (in the preferences)

**Comment by bricewge** [comment]
I tired the "Through shell" option but it doesn't change anything. The problem is not only graphical because I can't acces the password under directories with accents, when ask to displayed it the password field is empty. The other directories, without fancy characters, aren't affected.

Here is a screen-shot of the problematic directory:
![passff](https://cloud.githubusercontent.com/assets/5525646/7386916/330ba106-ee59-11e4-9628-aff321b4589e.png)

I'm using firefox 37.0.2 under a up-to-date Archlinux.

**Comment by jvenant** [comment]
hmm, that's weird. I'm pretty sure this is about your environment. Could you also try launching Firefox from your command line ? the same one you use to execute pass directly.

**Comment by bricewge** [comment]
Launching Firefox from the command line – the same which I use to acces pass – doesn't change anything, nor using "Through shell" or "Direct call". Unfortunately I had to reinstall my box from scratch this weekend, so it doesn't look to me this issue come from some custom config I did since it's still present in my new install.

I'm usually using zsh, but it also work with bash, here is a dump of my [env](https://gist.github.com/bricewge/c71cc7973ba5b4214bb6).

**Comment by jvenant** [comment]
Could you also activate the debug mode and give me output from the web console for PassFF please

Thank you

**Comment by bricewge** [comment]
I just tried to debug the addon, but I don't know how to, sorry. The console output nothing, but it came from me as it's the same with my others addons.

Here is the return for the ls
```
drwx------ 1 1000 3013  78 mars  29 20:05 Université
```

**Comment by jvenant** [comment]
Sorry for the delay, I didn't see your answer.
To enable debug mode, just go in the addon preferences and check the "Enable logs" check box at the bottom of the dialog box. You then have to open the Browser console (Tools/Web Developper/Browser console)
You should see many lines about passff. You could Filter on "[PassFF]" if you want

**Comment by bricewge** [comment]
I tried to debug it the way you explained to me, but I wasn't successful. Nothing about `passff` was showing off in the Browser console.
If you have any idea how I can report to you more useful information let me know. Note that the bug is still present.

**Comment by jvenant** [comment]
Please also check that in the browser console window,  in the Logging menu, all the checkboxes are checked.

**Comment by bricewge** [comment]
Yeah! I finally managed to get thoses logs! In the `Web Developper` menu I was mistaking `Web console` with `Browser console`... My bad.

Anyhow here is the log I got when trying to copy a password:
```
"[PassFF]" "List item selected" click { target: <label#passff-menu-label8>, buttons: 1, clientX: 366, clientY: 311, layerX: 115, layerY: 196 } bootstrap.js:31
"[PassFF]" "Create item menu" Object { depth: 0, key: "Universit\303\251", children: Array[3], parent: null, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "Create children menu list" Array [ Object, Object, Object ] false bootstrap.js:31
"[PassFF]" "List item selected" click { target: <label#passff-menu-label0>, buttons: 1, clientX: 353, clientY: 185, layerX: 102, layerY: 37 } bootstrap.js:31
"[PassFF]" "Create item menu" Object { depth: 1, key: "BU", children: Array[0], parent: Object, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "Create leaf menu list" Object { depth: 1, key: "BU", children: Array[0], parent: Object, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "copy to clipboard" click { target: <hbox#passff-menu-hbox5>, buttons: 1, clientX: 357, clientY: 301, layerX: 106, layerY: 153 } bootstrap.js:31
"[PassFF]" "Execute pass" Object { command: "/usr/bin/pass", arguments: Array[1], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done() } bootstrap.js:31
"[PassFF]" "[subprocess]" "getlimit: maxFD=1024
" bootstrap.js:31
"[PassFF]" "[subprocess]" "subprocess started; got PID 4468
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Closing Stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: waitpid signaled subprocess stop, exitcode=256
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: waitpid returned with errno=10
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stdout closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 58 bytes from stderr
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 0 bytes from stderr
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stderr closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Cleanup called
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "pass script execution ok" bootstrap.js:32
```

**Comment by phryneas** [comment]
Hmm.. could you please try the following?

`export LANG=fr_FR.ISO-8859-1`
and then start firefox from the same console?

**Comment by bricewge** [comment]
Here it is, but it looks the same.

```
"[PassFF]" "List item selected" click { target: <label#passff-menu-label8>, buttons: 1, clientX: 314, clientY: 307, layerX: 63, layerY: 192 } bootstrap.js:31
"[PassFF]" "Create item menu" Object { depth: 0, key: "Universit\303\251", children: Array[3], parent: null, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "Create children menu list" Array [ Object, Object, Object ] false bootstrap.js:31
"[PassFF]" "List item selected" click { target: <label#passff-menu-label0>, buttons: 1, clientX: 311, clientY: 186, layerX: 60, layerY: 38 } bootstrap.js:31
"[PassFF]" "Create item menu" Object { depth: 1, key: "BU", children: Array[0], parent: Object, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "Create leaf menu list" Object { depth: 1, key: "BU", children: Array[0], parent: Object, isLeaf: PassFF.Pass.initItems/item.isLeaf(), hasFields: PassFF.Pass.initItems/item.hasFields(), isField: PassFF.Pass.initItems/item.isField(), fullKey: PassFF.Pass.initItems/item.fullKey() } bootstrap.js:31
"[PassFF]" "copy to clipboard" click { target: <label#passff-menu-label4>, buttons: 1, clientX: 318, clientY: 264, layerX: 67, layerY: 126 } bootstrap.js:31
"[PassFF]" "Execute pass" Object { command: "/usr/bin/pass", arguments: Array[1], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done() } bootstrap.js:31
"[PassFF]" "[subprocess]" "getlimit: maxFD=1024
" bootstrap.js:31
"[PassFF]" "[subprocess]" "subprocess started; got PID 9327
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Closing Stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: waitpid returned with errno=10
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: waitpid signaled subprocess stop, exitcode=256
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stdout closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 58 bytes from stderr
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 0 bytes from stderr
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stderr closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Cleanup called
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "pass script execution ko" 256 "Error: Universit\303\251/BU is not in the password store.
" "" bootstrap.js:33
TypeError: passwordData is undefined menu.js:240:32
```

**Comment by jvenant** [comment]
1) After the addon initialization or after a refresh you should have a log line with "Found Items".
Could you expend it and see how "Université" is displayed.
2) Could you also try with a clean Firefox configuration ? Something like that :
* Rename your .mozilla in .mozilla.bak
* Start Firefox install the addon and test
* Stop Firefox
* Delete .mozilla
* Rename .mozilla.bak in .mozilla

**Comment by bricewge** [comment]
I did this with a clean Firefox configuration.
![passff](https://cloud.githubusercontent.com/assets/5525646/8279652/b702f07a-18d6-11e5-947c-b45595f81cdf.png)

Is it sufficient or you need the see all of the "Object"?

**Comment by jvenant** [comment]
One more thing (sorry ^_^)
could you give me details of arguments and environment arrays of the "Execute pass" log line

**Comment by jvenant** [comment]
What shell do you use when you execute pass script from the CLI ?

**Comment by bricewge** [comment]
No problem.
Arguments of "Execute pass" is empty, here is the environment arrays :
![passff01](https://cloud.githubusercontent.com/assets/5525646/8280035/dc522c76-18d9-11e5-9147-bbb9d4cdc11c.png)


I'm using `zsh` but it's also working fine with `bash`.

**Comment by jvenant** [comment]
might be something about the tree and charsets again...
Using your CLI, could you try to : 
* go in your password-store folder (.password-store)
* execute "export TREE_CHARSET=ISO-8859-1"
* execute "tree"

Is Université.gpg displayed correctly ?
@phryneas if you have any idea or clue...? I know you're very comfortable now with tree and charsets ^_^

**Comment by bricewge** [comment]
Yes it is displayed correctly:
```
&middot;-- Université
    |-- BU.gpg
```

**Comment by jvenant** [comment]
I put a temporary debug version displaying extra debug in the log here [PassFF 0.1.27-debug-do-not-use](http://invicem.pro/passff.xpi).
it will just add the pass tree output in the debug console. So nothing very sensible.

**Comment by bricewge** [comment]
Interesting, here it's displayed wrongly.
```
"[PassFF]" "stdout" "Password Store
&middot;-- Universit\303\251
    |-- BU
    &middot;-- CROUS
"
```

**Comment by jvenant** [comment]
what is the output for "locale" command ?

**Comment by bricewge** [comment]
```
$  locale
LANG=fr_FR.utf8
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE=fr_FR.UTF-8
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

**Comment by jvenant** [comment]
could you also try to browse your filesystem using Firefox : type file:///home/bricewge/.password-store/ in the url bar and browse to Université to see if the encoding is correct

**Comment by bricewge** [comment]
Browsing file:///home/bricewge/.password-store/ in Firefox show a correct encoding.

**Comment by jvenant** [comment]
Got a new "special version" for you. Same location as before.
This time, in the log you should see a "TEST LOCALE" with the output of the locale command from your Firefox context.

**Comment by bricewge** [comment]
Starting Firefox with this version give me this error:
`Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]`

Here is the new log:
```
"[PassFF]" "Refresh" click { target: <button#passff-refresh-menuitem>, buttons: 1, clientX: 1086, clientY: 354, layerX: 134, layerY: 278 } bootstrap.js:31
"[PassFF]" "Preferences initialised" Object { passwordInputNames: Array[3], loginInputNames: Array[4], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/usr/bin/pass", commandArgs: Array[1], shell: "/bin/bash", shellArgs: Array[1], home: "/home/bricewge", 10 de plus… } bootstrap.js:32
"[PassFF]" "Execute pass" Object { command: "locale", arguments: Array[0], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executeTest/params.done() } bootstrap.js:31
The object cannot be linked to the inspector without a toolbox console-output.js:3138:0
"[PassFF]" "[PassFF]" "Error executing pass script" Exception { message: "Component returned failure code: 0x…", result: 2152857601, name: "NS_ERROR_FILE_UNRECOGNIZED_PATH", filename: "chrome://passff/content/subprocess.…", lineNumber: 372, columnNumber: 0, inner: null, data: null, stack: "getCommandStr@chrome://passff/conte…", location: XPCWrappedNative_NoHelper } bootstrap.js:34
"[PassFF]" "TEST LOCALE" undefined bootstrap.js:31
"[PassFF]" "Execute pass" Object { command: "/usr/bin/pass", arguments: Array[0], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done() } bootstrap.js:31
"[PassFF]" "[subprocess]" "getlimit: maxFD=1024
" bootstrap.js:31
"[PassFF]" "[subprocess]" "subprocess started; got PID 21672
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Closing Stdin
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: initialising library with libc.so.6
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 15 bytes from stdout
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stderr: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stderr closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "got 763 bytes from stdout
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: waitpid signaled subprocess stop, exitcode=0
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Got msg from stdout: poll returned HUP
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Pipe stdout closed
" bootstrap.js:31
"[PassFF]" "[subprocess]" "Cleanup called
" bootstrap.js:31
"[PassFF]" "[subprocess]" "trying to close stdin
" bootstrap.js:31
"[PassFF]" "pass script execution ok" bootstrap.js:32
"[PassFF]" "Found Items" Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object ] bootstrap.js:31
"[PassFF]" "createContextualMenu" "about:home" bootstrap.js:31
"[PassFF]" "Search items for :" URL { href: "about:home", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "", search: "" } bootstrap.js:31
"[PassFF]" "matchingItems : " Array [  ] bootstrap.js:31
"[PassFF]" "Create children menu list" Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object ] undefined bootstrap.js:31
```

Thanks a lot for taking the time to chase this nasty bug! (:

**Comment by jvenant** [comment]
You are not using the "through shell" invocation method. Could you try
again using it

On Mon, Jun 22, 2015 at 4:08 PM bricewge <notifications@github.com> wrote:

> Starting Firefox with this version give me this error:
> Component returned failure code: 0x80520001
> (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]
>
> Here is the new log:
>
> "[PassFF]" "Refresh" click { target: <button#passff-refresh-menuitem>, buttons: 1, clientX: 1086, clientY: 354, layerX: 134, layerY: 278 } bootstrap.js:31
> "[PassFF]" "Preferences initialised" Object { passwordInputNames: Array[3], loginInputNames: Array[4], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/usr/bin/pass", commandArgs: Array[1], shell: "/bin/bash", shellArgs: Array[1], home: "/home/bricewge", 10 de plus… } bootstrap.js:32
> "[PassFF]" "Execute pass" Object { command: "locale", arguments: Array[0], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executeTest/params.done() } bootstrap.js:31
> The object cannot be linked to the inspector without a toolbox console-output.js:3138:0
> "[PassFF]" "[PassFF]" "Error executing pass script" Exception { message: "Component returned failure code: 0x…", result: 2152857601, name: "NS_ERROR_FILE_UNRECOGNIZED_PATH", filename: "chrome://passff/content/subprocess.…", lineNumber: 372, columnNumber: 0, inner: null, data: null, stack: "getCommandStr@chrome://passff/conte…", location: XPCWrappedNative_NoHelper } bootstrap.js:34
> "[PassFF]" "TEST LOCALE" undefined bootstrap.js:31
> "[PassFF]" "Execute pass" Object { command: "/usr/bin/pass", arguments: Array[0], environment: Array[6], charset: "UTF-8", mergeStderr: false, done: PassFF.Pass.executePass/params.done() } bootstrap.js:31
> "[PassFF]" "[subprocess]" "getlimit: maxFD=1024
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "subprocess started; got PID 21672
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "trying to close stdin
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Closing Stdin
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Got msg from stderr: initialising library with libc.so.6
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Got msg from stdout: initialising library with libc.so.6
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "got 15 bytes from stdout
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Got msg from stderr: poll returned HUP
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Pipe stderr closed
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "got 763 bytes from stdout
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Got msg from stdout: waitpid signaled subprocess stop, exitcode=0
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Got msg from stdout: poll returned HUP
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Pipe stdout closed
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "Cleanup called
> " bootstrap.js:31
> "[PassFF]" "[subprocess]" "trying to close stdin
> " bootstrap.js:31
> "[PassFF]" "pass script execution ok" bootstrap.js:32
> "[PassFF]" "Found Items" Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object ] bootstrap.js:31
> "[PassFF]" "createContextualMenu" "about:home" bootstrap.js:31
> "[PassFF]" "Search items for :" URL { href: "about:home", origin: "null", protocol: "about:", username: "", password: "", host: "", hostname: "", port: "", pathname: "", search: "" } bootstrap.js:31
> "[PassFF]" "matchingItems : " Array [  ] bootstrap.js:31
> "[PassFF]" "Create children menu list" Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object ] undefined bootstrap.js:31
>
> Thanks a lot for taking the time to chase this nasty bug! (:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jvenant/passff/issues/63#issuecomment-114116825>.
>
-- 
Johan Venant
www.invicem.pro

**Comment by jvenant** [comment]
You are not using the "through shell" invocation method. Could you try again using it

**Comment by bricewge** [comment]
It's definitely better with "through shell":
```
"[PassFF]" "TEST LOCALE" "LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
"
```

**Comment by jvenant** [comment]
We are close I think. But next step will be on you ^_^.
For a reason I don't understand (linked to your environment...?), your locale configuration from inside firefox doesn't match the one from your shell.

That's why executing "tree" from your CLI give the good encoding but not from Firefox
Try executing "LC_ALL=POSIX tree" and you'll see. You'll reproduce the wrong behavior from your CLI

Did you try with a clean firefox configuration as I suggest this morning ? (5 hours ago)

**Comment by bricewge** [comment]
My locale is set in `~/.profile` so its evaluated by `bash` and by `zsh` (in `~/.zprofile`). And `/etc/locale.conf` contain `LANG=fr_FR.UTF-8`. So I really don't understand why I get a random locale only in `passff`. Where should I set it to get it working nicely.
Since your suggestion about using a clean config for Firefox, all the logs came from it.

**Comment by jvenant** [comment]
It can be caused by so many things. I have no idea about what can do this in your specific case.
Do you use KDM ? I google this a little bit and found some issues about kdm and locales with X applications
here : https://bbs.archlinux.org/viewtopic.php?id=38675
and here : http://linuxfr.org/forums/linux-general/posts/locales-diff%C3%A9rentes-entre-la-console-et-x

**Comment by phryneas** [comment]
your ~/.profile is evaluated by zsh only if you additionally pass the `--login` argument - could you please try that as shell argument?

**Comment by bricewge** [comment]
@phryneas You fixed it!! Thanks.
So if I understand it well my locale X session is `POSIX`. I didn't remark it because my terminal overwrite those value when it start. So I may stumbled upon a similar issue any other X program

**Comment by phryneas** [comment]
We really need a troubleshooting flowchart, we keep forgetting that part although it helps almost every time xD

**Comment by jvenant** [comment]
I didn't ask about the --login parameter because it is present by default when you activate the through shell invocation. I though it was already present

**Comment by phryneas** [comment]
I fear it isn't - or am I looking at the wrong location?

https://github.com/jvenant/passff/blob/master/src/modules/preferences.js :

        shell                 : "/bin/bash",
        shellArgs             : "",

**Comment by jvenant** [comment]
My bad : bad assumption. Sorry.
Maybe it would be a good idea to add it by default.
I don't know if it is a standard parameter...?

**Comment by phryneas** [comment]
The way we are using it (to get the user's standard environment that may be different between shell and GUI) it should be default.
I'll make a pull request.
