### ISSUE TITLE
No P on the toolbar

### ISSUE THREAD

**Issue by acwatkins** [jvenant/passff#64]
Tried reinstalling, enabling disabling, no icon on the toolbar...

OS: Debian Jessie
Browser:  IceWeasel 31.6.0
Plugin Version v1-pre-release-23

**Comment by phryneas** [comment]
is your navigation bar hidden maybe?

https://github.com/jvenant/passff/issues/37

**Comment by acwatkins** [comment]
No, mostly default nav bar.

**Comment by phryneas** [comment]
Can you check if there is anything logged in the browser console?
Enable logs, then press Ctrl-Shift-j or check in Tools/Web Developer/Browser Console.

**Comment by acwatkins** [comment]
Upon disable/enable I get the following message.

1431983392992	addons.xpi	WARN	Error loading bootstrap.js for passff@invicem.pro: SyntaxError: property name menubar appears more than once in object literal (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/user/.mozilla/firefox/9qs17njn.default/extensions/passff@invicem.pro.xpi!/bootstrap.js:86:17) JS Stack trace: @XPIProvider.jsm:4136:1 < XPI_loadBootstrapScope@XPIProvider.jsm:4136:1 < XPI_callBootstrapMethod@XPIProvider.jsm:4205:9 < XPI_updateAddonDisabledState@XPIProvider.jsm:4356:1 < AddonWrapper_userDisabledSetter@XPIProvider.jsm:6647:9 < set_userDisabled@extensions.xml:1084:11 < oncommand@about:addons:1:1
1431983392992	addons.xpi	WARN	Add-on passff@invicem.pro is missing bootstrap method startup

**Comment by phryneas** [comment]
okay, that's one for @jvenant - I know only the pass side of passff, not the firefox side :/

**Comment by jvenant** [comment]
Hi,

this bug has already been fixed by @innir [here](https://github.com/jvenant/passff/pull/62).
But I didn't create a release for that. Sorry :confused:
I juste made one : [v1-pre-release-24](https://github.com/jvenant/passff/releases/tag/v1-pre-release-24)

**Comment by acwatkins** [comment]
Worked, thanks
