### ISSUE TITLE
Menu items misplaced on OS X

### ISSUE THREAD

**Issue by sometoby** [jvenant/passff#65]
Before installing passff:
![screen shot 2015-05-24 at 18 53 55](https://cloud.githubusercontent.com/assets/1444515/7788697/c9a5ca78-0246-11e5-80e0-98796ce79149.png)

After installing passff:
![screen shot 2015-05-24 at 18 52 24](https://cloud.githubusercontent.com/assets/1444515/7788699/cf8946fe-0246-11e5-9a55-91385fa537b5.png)
![screen shot 2015-05-24 at 18 55 27](https://cloud.githubusercontent.com/assets/1444515/7788700/cfb01a90-0246-11e5-828d-5a3015408e21.png)

The two menu buttons at the bottom of the passff dialog are not only misplaced, but also replace the default Firefox menu bar.

I'm using the latest passff version (v1-pre-release-24), Firefox 38.0.1 and OS X 10.10.3.

**Comment by jvenant** [comment]
Hmm... Very annoying I presume ^_^.
Sorry about that.
I don't have a Mac. And I don't know here this behavior can come from. I'll have to google that a little bit

**Comment by sometoby** [comment]
I'll have a closer look at this myself, maybe I can find a fix. Haven't done Firefox addons before, so no promises.

**Comment by sometoby** [comment]
As far as I understand it, this could be solved by using two buttons instead of a menu bar. Would this be an acceptable solution?

**Comment by jvenant** [comment]
Sure it will. I don't like this buttons menu anyway ^_^

**Comment by sometoby** [comment]
When will you be able to implement this?

**Comment by jvenant** [comment]
I have stuff to do shortly on the addon about the new Mozilla security policy (#66).
I'll try to put a fix about this issue in the next release.
But you know : wife, children, work, diy,... I can't give any guaranty about when it will be done.

**Comment by jvenant** [comment]
Should be fixed in the last  release [here](https://github.com/jvenant/passff/releases/tag/v1-pre-release-25)

Give it a try.
Let me know if you have any issue with it

**Comment by sometoby** [comment]
Worked beautifully. Thank you for the quick fix!
