### ISSUE TITLE
Mozilla Addons/Extension Signing

### ISSUE THREAD

**Issue by tr37ion** [jvenant/passff#66]
I just wanted to make you aware of the situation that Mozilla Addons will soon need signing. Have a look at https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by jvenant** [comment]
Yes, thank you. I saw that. Put it in my todo list ^_^

**Comment by jvenant** [comment]
The addon is stuck in the mozilla full review queue since Dec 2, 2014

**Comment by toupeira** [comment]
Just FYI [Firefox 42 will block unsigned extensions](https://wiki.mozilla.org/Addons/Extension_Signing), so I assume this will show up in the nightlies soon if it hasn't already.

**Comment by viq** [comment]
[Firefox 40 already does](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox)

Whom do we pester to get the review process accelerated?

**Comment by phryneas** [comment]
They are stating that 
> Files submitted for signing will go through an automated review process. If they pass this review, they are automatically signed and sent back to the developer. This process should normally take seconds. If the file doesn't pass review, the developer will have the option to request a manual review, which should take less than two days. This is not the same process that currently applies to AMO add-ons, which has been typically slower. 

so I'm a bit irritated that it takes this long. Maybe resubmit?

**Comment by toupeira** [comment]
It might be related to this part on https://developer.mozilla.org/en-US/Add-ons/Add-on_guidelines:

> - Add-ons must either be installed using the add-on web install system, or be approved by the user using the install opt-in dialog.
>    - We want our users to know what they are installing so that they are not unpleasantly surprised by changes they did not expect. We also want them to know what to remove if they decide not to keep it.
>   - Add-ons installed through application installers should use the Windows Registry or equivalent global install methods so that Firefox displays the opt-in screen. The opt-in screen must not be tampered with in any way, including overlaying additional information or images on top of it.

As far as I know passff isn't available on addons.mozilla.org, right? Unfortunately they don't explain what those "equivalent global install methods" are for platforms other than Windows.

**Comment by toupeira** [comment]
Oh and also found this on https://wiki.mozilla.org/Addons/Extension_Signing:

> How do I get my add-ons signed if they are not hosted on AMO?
>
>    You will need to create an AMO account and submit your add-on. There will be an option where you indicate the add-on won't be listed on AMO, and you'll be able to submit your add-on files without having them published on the site.

So now I realize you probably already did that... sorry for the noise :)

**Comment by jvenant** [comment]
Still in the mozzilla full review queue.

I didn't see anything in the interface about how to sign the addon without going through the review process (at least preliminarily)
I'm afraid that changing anything will reset our position in the queue. So for now, I prefer to don't touch anything. If you have any suggestion on how to accelerate the process or how to sign the addon without loosing our queue position, let me know.

**Comment by tr37ion** [comment]
You may ask in IRC irc.mozilla.org channel #amo for its position in the queue.

**Comment by tr37ion** [comment]
@jvenant yes, you better wait then for the approval. The lastest version you submitted is of March (as they told me at irc.mozilla.org #amo). It has preliminary approval and considering the current conditions it is quite normal. Also it seems someone submitted a similar or even the same version recently. I'm a bit confused here. Maybe it is better you investigate this :)

**Comment by jvenant** [comment]
This is what I have currently in the amo console

![2015-08-13--1439448994_1001x304_scrot](https://cloud.githubusercontent.com/assets/1199901/9244247/d59e71da-4199-11e5-91fb-f5600305747b.png)

The fact is that the queue position doesn't mean anything because sometime it increase, sometime it decrease... and most of the time it is stucked ! ^_^
Probably bigger addons have some kind of priority on ours

I don't know any thing about this other similar version submitted to amo...
I'm going to ask to @sometoby. He works a lot on the plugin at the moment. Maybe he tried something.

**Comment by sometoby** [comment]
I haven't submitted anything, no.

**Comment by toupeira** [comment]
@jvenant I have a feeling the low priority is connected to the name of the extension, even if only because it starts with the last letter in the alphabet ;-) Why not call it "PassFF" like it appears in the Add-ons manager?

**Comment by josephholsten** [comment]
Is there anything I can do to help with this?

**Comment by jvenant** [comment]
Queue Position: 10 of 207
I have no idea of how to accelerate the process.
I submit a version in December of 2014 and it's still not reviewed... And it's an old version....
So I don't know what you can do.
Probably be hire by the mozilla fondation as an addon reviewer would be the fastest way ^_^

**Comment by toupeira** [comment]
Hmm maybe resubmit the latest version with the proper name, i.e. "PassFF" instead of "zxc24 pass manager addon"? Might also help if they process them alphabetically ;-)

**Comment by jvenant** [comment]
I'm afraid this will reset PassFF position in the queue....

**Comment by Arenlor** [comment]
The queue position is almost pointless. They sort of ignore it now, what they look at is size, complexity of the code, what OS it works on, and how old the review is. I would suggest getting on #amo-editors on irc.mozilla.org and asking there.

Have you addressed the concerns brought up by the reviewer from your Aug 1 2014 review?

**Comment by jvenant** [comment]
Tada ! 
https://addons.mozilla.org/en-US/firefox/addon/zx2c4-pass-manager-addon/

**Comment by jvenant** [comment]
Now, I'll have to submit a more recent version...

**Comment by phryneas** [comment]
And please flag the new version as "compatible with windows" ;)

**Comment by avrelaun** [comment]
@jvenant Your link is broken, was it taken down ?

**Comment by jvenant** [comment]
Sorry I changed the name of the addon as suggested in an other ticket.

Now it is 
https://addons.mozilla.org/en-US/firefox/addon/passff/
