### ISSUE TITLE
bash /usr/local/bin/pass hangs

### ISSUE THREAD

**Issue by faern** [jvenant/passff#71]
I'm on OSX 10.10.3 and Firefox 38.0.5 and I can't get passff to work at all.
Whenever I activate the plugin I instantly get a background processes running **bash /usr/local/bin/pass** that is consuming 100% CPU.
I have installed *pass* via homebrew and have thus changed the path in the plugin preferences to /usr/local/bin/pass.

Sidenote: The first time I installed the plugin I had the P icon in the toolbar, but now that won't even show up even if I reinstall the plugin.

I don't have very much more information right now. Any log I can attach or any debugging I can perform?

**Comment by sometoby** [comment]
I've had this problem too. Make sure your passff script settings match these:

![screen shot 2015-06-16 at 17 04 36](https://cloud.githubusercontent.com/assets/1444515/8186322/ddafa074-1449-11e5-908c-6e5fece17e54.png)

Obviously, change the home directory to your own or leave it blank.
This configuration has been working for me thus far.

**Comment by faern** [comment]
Interesting workaround. It did remove the blocking background process and gave back the toolbar icon. Now I just have to see if the rest works.
Thank you for the quick response and detailed fix!

**Comment by phryneas** [comment]
This is the old solution for this problem. 
The new solution is to use the `through shell` options with /bin/bash as "pass shell" and "/usr/local/bin/pass" as pass command - give it a try ;)

**Comment by jvenant** [comment]
Using the "through shell" approach should do the job too I think

**Comment by sometoby** [comment]
Unfortunately not. I attempted to use the fill function, but this still spawns bash processes that run at 100% processor usage. The password is also never inserted.
![screen shot 2015-06-16 at 17 21 56](https://cloud.githubusercontent.com/assets/1444515/8186726/3db5e6a2-144c-11e5-8bae-be83341d0211.png)

**Comment by phryneas** [comment]
and when you enter `--login` as shell line argument?

**Comment by phryneas** [comment]
as for the 100%: i suspect your .bashrc or .profile spawn something by default that waits for STDIN?

**Comment by sometoby** [comment]
Whops, could've thought of that myself. Adding the login option fixes it, thanks.

**Comment by faern** [comment]
I tried *through shell* before reporting this without any luck, but the **--login** option solved that. So now the process does not hang and I can search my password-store in FF, but I can't autofill. I will start a new issue on that.
