### ISSUE TITLE
Nothing autofills

### ISSUE THREAD

**Issue by faern** [jvenant/passff#73]
Hi.
I have OS X 10.10.3, Firefox 38.0.5, passff v1-pre-release-25.
I can look in my password-store from the plugin in the browser, so the plugin can read the password-store. However, I can't make it autofill in any way. I have created a very simple homepage:
```html
<html>
  <body>
    <input type="text" id="user" />
    <input type="password" id="password" />
  </body>
</html>
```
That I have placed under */Users/faern/index.html*
Then I created an entry in my password-store
```
$ pass insert -m www/index.html
SecretPassword
username: faern
url: file:///Users/faern/index.html
```
I go to file:///Users/faern/index.html in Firefox, open the plugin menu, select my www/index.html entry and select *fill*, nothing happens. It's exactly the same for every site I have tried. Where can I find some log from the plugin? I don't have very much errors to go on here.
Here is a screenshot of my plugin settings:
![passff screenshot](https://photos-1.dropbox.com/t/2/AAAj-G9EeuSSZGbUhogklWloJM26UjqOZ-Dc7lSLRvdKag/12/1659954/png/32x32/1/1434484800/0/2/passff-preferences.png/CLKoZSABIAIoASgCKAc/JghSZDCbfITKY_SXgJrVTaxRr3D_alw4OjR9jLsg3Xw?size=1280x960&size_mode=2)

**Comment by sometoby** [comment]
You can view the browser console under Tools > Web Developer > Browser Console. When "Enable logs" is ticket, passff will produce lots of debugging output there.

**Comment by jvenant** [comment]
I add a section about this in the readme

**Comment by faern** [comment]
Ah, I'm sorry I did not come up with that myself. I'm pretty sure I checked there, but I guess I forgot to have the logging flag on at that time or something. Ok The output gave me some clues to what is wrong. I have the same problem as #56
I will patch my pass with the provided link
