### ISSUE TITLE
Latest release doesn't use ctrl+y

### ISSUE THREAD

**Issue by t2d** [jvenant/passff#89]
In the README ctrl+y is named as hotkey.
But after first install, it actually was ctrl+alt+t, which is identical to opening a terminal.
Please reset the defaults.

**Comment by sometoby** [comment]
Likely caused by f8413a9. The default shortcut has been Ctrl+Alt+T since then.

I'm not sure if this is really a bug. Has the shortcut ever been Ctrl+Y before, or was it an unnoticed typo in the readme?

**Comment by jvenant** [comment]
I personally prefer ctrl+alt+t. But if there is a conflict with an other shortcut, obviously, we'll have to change it. So ctrl+y will be the new one... Except if there is also a conflict with it, or if you have a better idea

**Comment by sometoby** [comment]
Is Ctrl+Alt+T the default shortcut for a terminal in any major OS/DE?

If not, I think changing our defaults is a step in the wrong direction. Every user that uses Control+Alt+T for PassFF will have to change the shortcut back if they don't want to get used to Ctrl+Y.

@t2d Is there any reason you can't just change the shortcut in the preferences to resolve the conflict?

**Comment by t2d** [comment]
> Is Ctrl+Alt+T the default shortcut for a terminal in any major OS/DE?

Ubuntu

> 
> @t2d <https://github.com/t2d> Is there any reason you can't just change
> the shortcut in the preferences to resolve the conflict?

No problem, but in any case README and actual config should be in sync.

**Comment by sometoby** [comment]
In that case, changing the default is probably a good idea. According to https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly, Ctrl+Y is not used by anything. I'd say it's a good choice.

**Comment by sometoby** [comment]
@jvenant, are you ok with this change? If so, I'll commit it to master and rebase the code-style branch from #83.

**Comment by jvenant** [comment]
ok for me
