### ISSUE TITLE
Save password to pass

### ISSUE THREAD

**Issue by bigeagle** [jvenant/passff#92]
Hi, 
Thank you for providing this useful tool!
I wonder if it's possible to save password to pass, instead of firefox when login to a new site?

Cheers,
Justin

**Comment by phryneas** [comment]
Hi, we had some discussion on that here:
https://github.com/jvenant/passff/issues/46

You might want to take a look at https://github.com/gekmihesg/pass-manager but none of the authors of passff are involved there.

**Comment by bigeagle** [comment]
Thanks!
