### ISSUE TITLE
More menu rendering strangeness

### ISSUE THREAD

**Issue by phryneas** [jvenant/passff#95]
#94 got me experimenting.
While I cannot reproduce their bug, I found another one.

Steps to reproduce:

* right click passff icon
* move to menu
* open menu
* click passff icon

<img width="228" alt="2015-07-31 15_56_23-new issue jvenant_passff" src="https://cloud.githubusercontent.com/assets/4282439/9008793/f6455ec8-379c-11e5-8ac7-335eef15f8e8.png">

**Comment by sometoby** [comment]
That looks like it should actually be there, for switching back to the Firefox menu.

**Comment by phryneas** [comment]
Okay, that looks like the weirdest design decision from Mozilla ever, but it seems you're right, it acts as a kind of backward navigation.
