### ISSUE TITLE
Passff doesn't work with a non-default $GNUPGHOME location

### ISSUE THREAD

**Issue by GordanV** [jvenant/passff#96]
Hi

If you set the gnupg homedir via the GNUPGHOME environment variable, passff is not able to decrypt the password store and will always create a new $HOME/.gnupg directory.

[This](http://pastebin.com/6dKPATpE) patch fixes this and allows users to use a custom location for their GPG homedir.

Best regards

**Comment by jvenant** [comment]
Hi,

Thank you for your patch.

Does it works using the through shell invocation ? It could be a better approach because it will execute pass in the exact same environment than the CLI.

**Comment by GordanV** [comment]
Hello,

No, using shell invocation will do nothing (not even the $HOME/.gnupg dir will be created).
I played a bit around with it and the bash instance only sees those environment variables:

    PWD=/home/user
    SHLVL=1
    HOME=/home/user
    TREE_CHARSET=ISO-8859-1
    DISPLAY=:0.0
    _=/usr/bin/env

I created the listing by replacing the content of 'Pass command' with 'env > /home/user/env' in the passff settings and hitting refresh.

**Comment by phryneas** [comment]
Hi,
can you please try shell arguments `-l -i`?

**Comment by jvenant** [comment]
Arf ! I still forgot to specify that -l is required ^_^

**Comment by GordanV** [comment]
Hi,

I now used both the `-l` and the `-l -i` neither of which worked. The visible environment variables are:

    LIBGL_DRIVERS_PATH=/usr/lib/xorg/modules/dri/:/usr/lib32/xorg/modules/dri
    MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
    PWD=/home/user
    LANG=en_US.utf8
    SHLVL=1
    HOME=/home/user/
    TREE_CHARSET=ISO-8859-1
    DISPLAY=:0.0
    _=/usr/bin/env

I also found that the PASSWORD_STORE_DIR variable (and probably PASSWORD_STORE_GIT, didn't test) are not set when using shell invocation.
I assume that is because the getDirectEnvParams (in pass.js) is not call when going via the shell.

**Comment by phryneas** [comment]
The though of "shell invocation" is that passff does not interfere in 
any way with your env - that is the job of the shell you are using.

So if you are using the same shell you are using as a user, with the 
"-l"  (login) switch, it should load your .bash_profile, .zsh_profile or 
whatever configuration files your shell would load at login, to set 
environment variables there.

Are you using the same shell you are using on console?

**Comment by GordanV** [comment]
Oh now I understand. I set my environment variables in the [$HOME/.pam_environment](http://linux-pam.org/Linux-PAM-html/sag-pam_env.html) file. This is read at login by the window manager and therefor every process inside the  should inherit all those variables.
Anyhow, I will  just specify the GNUPGHOME and PASSWORD_STORE_DIR variables in $HOME/.profile, as this seems to work without a problem (with the options `-l -i`).

Thanks for your help.

**Comment by jvenant** [comment]
Any way I merged your patch on the master. It could help people wanting to use the old fashion pass invocation.
By the way, "through shell" invocation should be the default now. But I don't know how to do that without disturbing the users. Especially because it is very specific to the environment...

Thank you very much for your improvement.
