### ISSUE TITLE
Make passff work with input fields that use ids instead of names

### ISSUE THREAD

**Issue by GordanV** [jvenant/passff#98]
Hi,

While a login-form that is sent to a server always has the login and password fields identified by the name attribute, forms that are used in single-page JS applicationss sometimes omit names because the fields can be identified by their ids.

[This patch](http://pastebin.com/mj3VmVTE) tests an input field's id against the list of good names if it has no name attribute.

**Comment by jvenant** [comment]
Good improvement : committed on the master.
Thank you again for your contribution ^_^
